### PR TITLE
build: add dependabot config

### PR DESCRIPTION
**Pull request by vhashimotoo**
This allows disabling automatic updates internal electron modules (e.g. `electron-i18n`, `apps`), what we update when rolling update to indices.

NOTE: This overrides config what set upped in dependabot dashboard.

### CODE REVIEW

**Comment by BinaryMuse** [comment]
I don't think this is necessary; we can ignore the packages by using `@dependabot ignore this dependency` on the appropriate PRs (which I've done).

**Comment by BinaryMuse** [comment]
Hm, on second thought, the messages from dependabot say "unless you re-open this PR or *update it yourself*" so maybe we do need it

**Comment by vhashimotoo** [comment]
@BinaryMuse dependabot opens #68 after this be sets to ignoring it, so I think this makes sense.

**Comment by BinaryMuse** [comment]
I agree, let's do it

**Pull request merged**
